### ISSUE TITLE
Port to JavaScript

### ISSUE THREAD

**Issue by lillithrosepup** [DismissedGuy/Discord-QR-Auth-Client#1]
I know this is coded in python, but is there any way you can port this to javascript? I am using a [discord proxy](https://github.com/ZenithRogue/DiscordFlex) for my colleagues to bypass internet blocks, and I don't want to have to explain to everyone how to get their token. I'm hoping that this will be able to run inside the browser, then redirect to the main discord proxy. Is there any easy way to do this, or do I need to re-code it?

**Comment by malmeloo** [comment]
Hi!

I am not fluent enough in JavaScript to port this myself, but I'm sure it could be done considering that's how their official implementation works. I only just noticed that someone else [seems to have ported this project to node.js yesterday](https://github.com/ssense1337/Discord-QR-Auth-Client-JS), so you could probably use that as a reference.

If you do decide to port it and require assistance regarding the technical aspects of the protocol, I'll be happy to help. It's been a while since I've looked into all this, but it's still interesting nonetheless.

**Comment by ssense1337** [comment]
I made a discord bot out of this you can have a look at https://github.com/ssense1337/Discord-QR-Auth-Client-JS

**Comment by ssense1337** [comment]
My embed messages are in Thai language

**Comment by lillithrosepup** [comment]
Oh, that looks perfect. I don't know how I didn't see that when I was searching. Thanks for showing me!

**Comment by malmeloo** [comment]
I'll close this issue for now; if you need help just let me know or re-open it.
