### ISSUE TITLE
Connection closed with 403

### ISSUE THREAD

**Issue by ghost** [DismissedGuy/Discord-QR-Auth-Client#2]
Everytime, you try to connect to the websocket, it just closes it for 403 Forbidden,  please help

**Comment by malmeloo** [comment]
That's interesting... looks like discord is finally doing something against 3rd party clients. I'm currently going through my first week of uni so I'm not sure if/when I'll have time to look into this, especially since this project was really just meant to be a proof of concept.

In the meanwhile, if you or anyone else could provide me with some network dumps that'd be helpful (don't worry, i can't see your token or account info from network dumps alone, since the private key to decrypt the data is stored on your computer. That is, unless discord has rolled out a v2 that's less secure than v1...)

**Comment by andry08** [comment]
So, they only implemented a simple origin check.
I made a pull request, you can check it out.
